// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cases

// Injectors from injector.go:

func InitializeSimpleService(isErorr bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isErorr)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}
