// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cases

import (
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeSimpleService(isErorr bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isErorr)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitializeDatabaseRepository() (*DatabaseRepository, error) {
	databasePostgreSQL := NewDatabasePostgreSQL()
	databaseMongoDB := NewDatabaseMongoDB()
	databaseRepository := NewDatabaseRepository(databasePostgreSQL, databaseMongoDB)
	return databaseRepository, nil
}

func InitializeFooBarService() *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository)
	barRepository := NewBarRepository()
	barService := NewBarService(barRepository)
	fooBarService := NewFooBarService(fooService, barService)
	return fooBarService
}

// injector.go:

var fooSet = wire.NewSet(
	NewFooRepository,
	NewFooService,
)

var barSet = wire.NewSet(
	NewBarRepository,
	NewBarService,
)
